### ISSUE TITLE
[선로추가] 고무차륜 선로 / AGT Track

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS_Track#10]
### 필수 스프라이트

- 기본 그래픽
![AGT_TRACK](https://github.com/DTS-NewGRF/DTS_Track/assets/88026704/875f0e76-2d26-44de-8975-b85dc87fe0bb)

- 눈지형 그래픽
없음 (눈이 내리는 기후에서는 열선을 통해 궤도 위 눈을 녹이기 때문에 구현할 필요가 없을 것으로 판단됨)

- 울타리
https://github.com/DTS-NewGRF/DTS_Track/blob/main/src/RailBed/RailBed_Fence.png
의 세번째 그래픽

### 32bpp 스프라이트

없음

### 설명

그래픽 분활이 완료되지 않은 듯 보여 일단 기존 형식대로 작업하였습니다.

우리나라에서는 부산 도시철도 4호선, 의정부경전철, 신림선, 인천공항셔틀트레인 등에서 사용중인 방식입니다.

- 권장 선로코트: `LAGT`
- 호환되는 선로: `KRLR` (한국열차세트 경전철 선로와 호환 목적)
- 선로 최고속도: 100km/h (고무차륜 선로는 도시철도용으로만 사용됩니다.)
- 건널목 불가

**Comment by evepoi** [comment]
호환선로 `KRLR`은 본 선로세트에도 포함되어 있으므로, 호환선로가 없는 상태로 제작하겠습니다.
겹치는 관계로 고무차륜선로가 나오지 않습니다.
