### ISSUE TITLE
[선로추가] 과좌식 모노레일

### ISSUE THREAD

**Issue by JukjeonWani** [DTS-NewGRF/DTS_Track#13]
### 필수 스프라이트

![G_MONO](https://github.com/DTS-NewGRF/DTS_Track/assets/88026704/72408afd-8441-4d62-82ac-110328d3f3ce)

### 32bpp 스프라이트

없음

### 설명

권장 선로코드: `GMNO`
호환되는 선로: 없음
선로 최고속도: 80km/h
건널목 불가

실제로는 지상고가 방식으로 지어지나 게임 상에서의 구현이 어려울 것으로 판단되어 지상에 지어지는 방식으로 작업되었습니다.

한국열차세트의 경전철 선로 기반입니다. 어긋난 그래픽은 없는지 확인이 필요합니다.

**Comment by evepoi** [comment]
효율적인 구현을 위해 잠시 보류합니다.

**Comment by JukjeonWani** [comment]
![GMNO](https://github.com/DTS-NewGRF/DTS_Track/assets/88026704/cc972cd9-5bc1-4dc5-bf5c-edaf49835fbc)
어긋나는 선로 스프라이트 위치 조정한 그래픽입니다.

**Comment by JukjeonWani** [comment]
![GMNO](https://github.com/DTS-NewGRF/DTS_Track/assets/88026704/2a5f945a-9389-4d49-ba31-53469d3bf4a0)
대구도시철도 3000호대 전동차 운행시키면서 2차로 조정한 그래픽입니다.

**Comment by JukjeonWani** [comment]
다리 오버레이 및 터널 선로가 자연스럽게 이어지도록 한번 더 수정하였습니다.
![GMNO](https://github.com/DTS-NewGRF/DTS_Track/assets/88026704/e2b015a3-c7a5-45ed-9a27-8efb380cfbf6)

**Comment by JukjeonWani** [comment]
이슈 닫아도 됩니다~
@evepoi
